# Generated by Django 3.2.15 on 2022-08-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='invite',
            field=models.CharField(default='7fd28a1daaba4235b28a4f6cf3c8917e', max_length=32, verbose_name='invite code'),
        ),
    ]
