# Generated by Django 3.2.15 on 2022-08-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='invite',
            field=models.CharField(default='fdabee75d03f4078858fc296bc5b56f2', max_length=32, verbose_name='invite code'),
        ),
    ]
